export const GET_TOP_ALBUMS_REQUEST = 'GET_TOP_ALBUMS_REQUEST';
export const GET_TOP_ALBUMS_SUCCESS = 'GET_TOP_ALBUMS_SUCCESS';
export const GET_TOP_ALBUMS_ERROR = 'GET_TOP_ALBUMS_ERROR';

export const GET_ALBUM_INFO_REQUEST = 'GET_ALBUM_INFO_REQUEST';
export const GET_ALBUM_INFO_SUCCESS = 'GET_ALBUM_INFO_SUCCESS';
export const GET_ALBUM_INFO_ERROR = 'GET_ALBUM_INFO_ERROR';
