export const FETCH_MY_ARTIST_REQUEST = 'FETCH_MY_ARTIST_REQUEST';
export const FETCH_MY_ARTIST_SUCCESS = 'FETCH_MY_ARTIST_SUCCESS';
export const FETCH_MY_ARTIST_ERROR = 'FETCH_MY_ARTIST_ERROR';

export const SEARCH_ARTIST_REQUEST = 'SEARCH_ARTIST_REQUEST';
export const SEARCH_ARTIST_SUCCESS = 'SEARCH_ARTIST_SUCCESS';
export const SEARCH_ARTIST_ERROR = 'SEARCH_ARTIST_ERROR';
